name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    
    outputs:
      image_tag: ${{ steps.generate_tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate short SHA tag
        id: generate_tag
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ steps.generate_tag.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/hello-app:latest
          platforms: linux/amd64,linux/arm64

  create-pull-request:
    name: Create Pull Request in Manifests Repo
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Checkout manifests repository
        uses: actions/checkout@v4
        with:
          repository: PedrooHSN-Dev/hello-manifests
          ssh-key: true
          path: hello-manifests
          
      - name: Update manifest files
        run: |
          cd hello-manifests
          cd k8s
          NEW_TAG=${{ needs.build-and-push.outputs.image_tag }}
          
          sed -i 's|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:'$NEW_TAG'|' deployment.yaml
          sed -i 's|value:.*|value: "'$NEW_TAG'"|' deployment.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          path: hello-manifests
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'ci: update image to version ${{ needs.build-and-push.outputs.image_tag }}'
          title: 'Auto: Update image to version ${{ needs.build-and-push.outputs.image_tag }}'
          body: 'Automated PR to update image tag from CI pipeline.'
          branch: 'update-image-${{ needs.build-and-push.outputs.image_tag }}'
          delete-branch: true